data:extend({
  {
    type = "bool-setting",
    name = "bnl-enable",
    setting_type = "startup",
    default_value = true,
    order = "a",
  },
  {
    type = "bool-setting",
    name = "bnl-glow",
    setting_type = "startup",
    default_value = true,
    order = "a",
  },
  {
    type = "bool-setting",
    name = "bnl-include-mining-drills",
    setting_type = "startup",
    default_value = true,
    order = "a",
  },
  {
    type = "string-setting",
    name = "bnl-indicator-size",
    setting_type = "startup",
    default_value = "small",
    allowed_values = { "small", "medium", "large", "huge" },
    order = "a",
  },
  {
    type = "color-setting",
    name = "bnl-color-disabled",
    localised_name = { "mod-setting-name.bnl-color-setting", { "mod-setting-name.bnl-status-disabled" } },
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-full_output",
    localised_name = { "mod-setting-name.bnl-color-setting", { "mod-setting-name.bnl-status-full_output" } },
    setting_type = "startup",
    default_value = { r = 1, g = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-idle",
    localised_name = { "mod-setting-name.bnl-color-setting", { "mod-setting-name.bnl-status-idle" } },
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-insufficient_input",
    localised_name = { "mod-setting-name.bnl-color-setting", { "mod-setting-name.bnl-status-insufficient_input" } },
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-low_power",
    localised_name = { "mod-setting-name.bnl-color-setting", { "mod-setting-name.bnl-status-low_power" } },
    setting_type = "startup",
    default_value = { r = 1, g = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-no_minable_resources",
    localised_name = { "mod-setting-name.bnl-color-setting", { "mod-setting-name.bnl-status-no_minable_resources" } },
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-no_power",
    localised_name = { "mod-setting-name.bnl-color-setting", { "mod-setting-name.bnl-status-no_power" } },
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-working",
    localised_name = { "mod-setting-name.bnl-color-setting", { "mod-setting-name.bnl-status-working" } },
    setting_type = "startup",
    default_value = { g = 1 },
    order = "b",
  },
})
